name: Test

on:
  push:
    branches: ['**']
    tags-ignore: ['v*']
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      - run: npm ci
      - run: npm test
      - run: npm run build
